// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MyTrip {
	
	
	public partial class RecoverPassword {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblMsg;
		
		protected System.Web.UI.WebControls.Label lblPassword;
		
		protected System.Web.UI.WebControls.TextBox tbNewPass;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidatorPass;
		
		protected System.Web.UI.WebControls.Label lblRetypePass;
		
		protected System.Web.UI.WebControls.TextBox tbConfirmPass;
		
		protected System.Web.UI.WebControls.CompareValidator CompareValidatorPass;
		
		protected System.Web.UI.WebControls.Button btRecPass;
	}
}
