// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MyTrip {
	
	
	public partial class UserHome {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button btnSignOut;
		
		protected System.Web.UI.WebControls.Label lblSuccess;
		
		protected System.Web.UI.WebControls.TextBox tbName;
		
		protected System.Web.UI.WebControls.TextBox tbEmail;
		
		protected System.Web.UI.WebControls.TextBox tbPhone;
		
		protected System.Web.UI.WebControls.TextBox tbMessage;
		
		protected System.Web.UI.WebControls.Button btnSend;
		
		protected System.Web.UI.WebControls.Label lblMsg;
	}
}
